name: Lianhua Chi
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
gems:
  - jekyll-sitemap
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate
theme: minima


